### ISSUE TITLE
Add description for respository

### ISSUE THREAD

**Issue by Agrover112** [EXYNOS-999/meta_resource#13]
Adding a suitable description for repo making it easy for others to contribute and understanding the need ,theme of the repo.

**Comment by EXYNOS-999** [comment]
The name is inspired from https://meta-meta-resources.org/ and is apt, anyone who understands the word "meta" would appreciate the same.

**Comment by Agrover112** [comment]
About
No description, website, or topics provided.??
@EXYNOS-999  no need?

**Comment by EXYNOS-999** [comment]
No
