### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by rishistyping** [EXYNOS-999/meta_resource#43]
Setup WhatsApp+ Airtable workflow-- Airtable API + GH Actions + other CI/CD scripts.

**Comment by EXYNOS-999** [comment]
Setup WhatsApp+ Airtable workflow-- Airtable API + GH Actions + other CI/CD scripts.

**Comment by rishistyping** [comment]
https://github.com/wagtail/wagtail-airtable
https://github.com/wagtail/wagtail-airtable

**Comment by binarypheonix** [comment]
Make a Universal TODO list of all the tasks within the M68 org and the meta_resource project.

**Comment by rishistyping** [comment]
Done see: Projects.
